name: Generate Pac-Man and Galaga

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Pac-Man and Galaga
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: samuelerik-dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: pacman,galaga

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: dist
