name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: samuelerik-dev

          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?background=000000&color=yellow,orange,red

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: pacman-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
