```yaml
name: Generate Pac-Man and Galaga

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man and Galaga
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: samuelerik-dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: "pacman,galaga"

      - name: Push generated SVGs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
